### ISSUE TITLE
Can't get the Mini Pasre on OBS

### ISSUE THREAD

**Issue by wingprinces** [RainbowMage/OverlayPlugin#30]
i pretty like ur plugin for ACT
but there is a problem when i use OBS
OBS can't get the miniprase in windows catch, there is no option for choice
so can u release another version for OBS?

pretty thx you create this plugin!!!

**Comment by ezsoftware** [comment]
I have a modified version that *may* work for you in my fork, download the "Streamer" edition from here: https://github.com/ezsoftware/OverlayPlugin/releases/tag/v0.3.3.7.EZS.4

**Comment by Cleanse** [comment]
@ezsoftware What special settings do you use in OBS to get it to show up? I am only getting a black square.

**Comment by wingprinces** [comment]
u can use this plugin
it's base on rainbowmage
working in OBS without black square

link:
https://github.com/xtuaok/ACT_EnmityPlugin/releases

2015-09-01 9:08 GMT+08:00 Paul Lovato <notifications@github.com>:

**Comment by Cleanse** [comment]
I was using your version, but still get a black box. Is it because of Windows 10/8 cannot diable Aero?

**Comment by ezsoftware** [comment]
The issue is that chromium uses OpenGL to render the HTML.  Chromium is the rendering engine that Chrome uses.  RainbowMage's OverlayPlugin uses Chromium Embedded Framework to render, so all Overlay Plugin's overlays are rendered with OpenGL.  Now the issue with that is OBS does not support OpenGL windows.  You can see the same thing if you try to capture, for example, a Minecraft window in OBS.

OBS does support OpenGL for game capture mode and screen capture mode, but not window capture.

So the only way you can get OBS stream with the overlay is to either use Screen Capture and get your whole screen, or (what I do) use a game capture to capture the game, then create a screen capture that is just the size of my overlay and then align the screen capture in OBS to match with the game capture.

I'm not certain about @wingprinces's note about xtuaok's addon working, since xtuaok's addon uses RainbowMage's plugin, and by extension CEF, to render the window it should be subject to the same limitations.

**Comment by Cleanse** [comment]
@ezsoftware Thanks man.

**Comment by Cleanse** [comment]
@ezsoftware Do you know of the html file created when the ACT runs? The OBS CLR Browser Source Plugin might allow for this to work.

**Comment by ezsoftware** [comment]
@Cleanse OverlayPlugin doesn't create an html file, it loads the html from the selected url/file into a CEF browser on a form and then passes JSON data with parsing information to an event hook in the javascript on the browser which then has to update the browser's DOM accordingly.

However, ACT itself has the ability to run a webserver and display a simple parsing table which should be compatible with that plugin and will provide constantly updating parse results through a web page URL, though it won't be anything fancy like OverlayPlugin can generate.  You can find the options for that under Options > Output Display > ACT Web Server.

**Comment by RainbowMage** [comment]
Window style of the overlay windows are "tool window" which is not show in the Windows/Alt-Tab candidate. Some of the capturing software ignores tool window from window list.

And, some of the window capturing software is not support layered window which overlay windows uses. Please use softwares which supports that to capture overlay windows.

Alternative option I suggest is using [ActServer plugin](https://github.com/RainbowMage/ActServer) to show DPS on your broadcasting.
