### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bulldawgg** [RainbowMage/OverlayPlugin#4]
1/5/2015 12:13:04 PM: Warning: LoadConfig: System.IO.FileNotFoundException: Specified file is not exists.
File name: 'C:\Users\Max\AppData\Roaming\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml'
   at RainbowMage.OverlayPlugin.PluginConfig.LoadXml(String path) in c:\Users\XXX\Desktop\ACT\OverlayPlugin-master\OverlayPlugin\PluginConfig.cs:line 216
   at RainbowMage.OverlayPlugin.PluginMain.LoadConfig() in c:\Users\XXX\Desktop\ACT\OverlayPlugin-master\OverlayPlugin\PluginMain.cs:line 202

I don't understand what it is that isn't working. Could someone help me please?

**Comment by ezsoftware** [comment]
Did you copy all the files in your bin/release directory to the ACT directory?

**Comment by Bulldawgg** [comment]
Yes. They're in a sub folder within the directory of ACT.
http://imgur.com/kpVqCAg

**Comment by ezsoftware** [comment]
can you screenshot your overlayPlugin-master directory as well?

**Comment by Bulldawgg** [comment]
http://imgur.com/lthkGnh

**Comment by ezsoftware** [comment]
Alright, you've got me stumped.  Sorry, the version you're using is the same one I'm using and no issues for me.

**Comment by Bulldawgg** [comment]
I guess I'll use the act original overlay for now then. Thanks for your
help!

**Comment by BMCSamael** [comment]
When you added the plugin did you do it from where you downloaded/run it. 

That error is pointing at the app data directory which you shouldn't use necessarily.

I would take the files provided and put them in the act folder itself (typically thats C:\Program Files (x86)\Advanced Combat Tracker).   Then, if its there, delete the plugin config (in ACT) and re-add it just to be safe.

**Comment by RainbowMage** [comment]
Closed outdated issue.

Please report if you still have problem.

**Comment by glookie1** [comment]
I still have the same issue.
Plugin is installed in C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
Seems like it tries to load the config file %appdata%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml and fails (because yes it doesnt exist). Seems like there is a problem with the creation of this file. 

30.06.2015 08:13:00: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
30.06.2015 08:13:00: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\EnmityOverlay.dll
30.06.2015 08:13:01: Info: LoadAddons: Tamagawa.EnmityPlugin.OverlayAddonMain: Initialized
30.06.2015 08:13:01: Warning: LoadConfig: System.IO.FileNotFoundException: Specified file is not exists.
Dateiname: '%appdata%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml'
   bei RainbowMage.OverlayPlugin.PluginConfig.LoadXml(String pluginDirectory, String path) in c:\Users\john_000\Repos\Personal\OverlayPlugin\OverlayPlugin.Core\PluginConfig.cs:Zeile 274.
   bei RainbowMage.OverlayPlugin.PluginMain.LoadConfig() in c:\Users\john_000\Repos\Personal\OverlayPlugin\OverlayPlugin.Core\PluginMain.cs:Zeile 250.
30.06.2015 08:13:01: Info: LoadConfig: Creating new configuration.
30.06.2015 08:13:01: Info: InitPlugin: Initialized.

My guess is that if you have a correct xml file in the specified location for the initial launch, it will work flawlessly.

**Comment by glookie1** [comment]
Okay, I found a fix: if you have the x86 version of ACT installed, you will need the x86 version of the plugin. (Is there even an x64 version of ACT?)
Once I replaced that, it now works perfectly. So there might be a problem with the way you handle file creation on x64.

**Comment by ezsoftware** [comment]
Yes, ACT has a 64 bit version, the latest versions of ACT (for several months now...) come with both a 64 and 32 bit version.  The 64 bit version is the Advanced Combat Tracker.exe while the 32 bit version is ACT_x86.exe but if you run the 64 bit version on a 32 bit system, it will just launch ACT_x86 instead so the single Advanced Combat Tracker.exe is compatible with both.

**Comment by whitemoonp** [comment]
Hi, I've read a bunch of websites and stuff trying to fix this. My .net is up to date, i have tried x64 and x86, and as soon as i try to use the over lay, i get the error.
Any ideas? :c

2/16/2018 6:46:06 PM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin-0.3.3.8-x64-full
2/16/2018 6:46:06 PM: Warning: LoadConfig: System.IO.FileNotFoundException: Specified file is not exists.
File name: 'C:\Users\white\AppData\Roaming\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml'
   at RainbowMage.OverlayPlugin.PluginConfig.LoadXml(String pluginDirectory, String path)
   at RainbowMage.OverlayPlugin.PluginMain.LoadConfig()
2/16/2018 6:46:06 PM: Info: LoadConfig: Creating new configuration.
2/16/2018 6:46:06 PM: Info: InitPlugin: Initialized.
